name: Run Modelling

on:
  push:
    paths:
      - "MIProject/**"
      - ".github/workflows/modelling.yml"
  workflow_dispatch:

jobs:
  modelling:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      # Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      # Install dependencies (dijalankan di MIProject)
      - name: Install dependencies
        working-directory: MIProject
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install mlflow

      # Run Modelling Script (dijalankan di MIProject)
      - name: Run Modelling Script
        working-directory: MIProject
        run: python modelling.py

      # Upload MLflow Artifacts
      - name: Upload MLflow Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: training-results
          path: MIProject/mlruns/
          retention-days: 30
