name: Run Modelling

on:
  push:
    paths:
      - "MIProject/**"
      - ".github/workflows/modelling.yml"
  workflow_dispatch:

jobs:
  modelling:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4 # Menggunakan versi terbaru

      - name: Set up Python
        uses: actions/setup-python@v5 # Menggunakan versi terbaru
        with:
          python-version: "3.10"

      # Install dependencies menggunakan working-directory
      - name: Install dependencies
        working-directory: MIProject
        run: |
          echo "Mengupgrade pip dan menginstal dependensi..."
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install mlflow # Instalasi eksplisit untuk memastikan

      # Run Modelling Script menggunakan working-directory
      - name: Run Modelling Script
        working-directory: MIProject
        run: python modelling.py

      # Upload MLflow Artifacts
      - name: Upload MLflow Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: training-results
          path: MIProject/mlruns/ # Path relatif dari root repo
          retention-days: 30